<div class="col-md-4 col-sm-12 hide" id="pv_summary">
	<img src="/images/4hhb/4HHB_PVRainbow.jpg" class="img-thumbnail main-image">
	<!-- Group button -->
	<p>
		<strong>Symmetry</strong>: C2 | <strong>Stoichiometry</strong>: Hetero 4-mer - A2B2<br>
		<strong>Generated</strong>: Biological assembly 1 assigned by authors and generated by PISA (software)
	</p>
	<div class="btn-group pull-left" role="group">
	  	<div class="btn-group">
		    <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
		      PV Viewer Selected
		      <span class="caret"></span>
		    </button>
		    <ul class="dropdown-menu DropdownChangeGallery" role="menu">
		      <li><a href="#ImageGallery">Image Gallery</a></li>
			  <li class="active"><a href="#PVViewer">PV Viewer</a></li>
		      <li><a href="#">Jmol Viewer</a></li>
			  <li><a href="#">Simple Viewer</a></li>
			  <li><a href="#">Protein Workshop</a></li>
		    </ul>
		  </div>
	
		<div class="btn-group">
		  <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
		    Bioassembly Unit 1 <span class="caret"></span>
		  </button>
		  <ul class="dropdown-menu" role="menu">
		    <li><a href="#">Assymetric Unit</a></li>
		    <li class="active"><a href="#" >Bioassembly Unit 1</a></li>
		    <li><a href="#">Bioassembly Unit 2</a></li>
		  </ul>
		</div>
	  
	</div>	
</div>