<div class="panel panel-default">
  <div class="panel-body" id="structureimagesection">
	<div id="carousel-structuregallery" class="carousel slide" data-ride="carousel">
	  <!-- Indicators -->
	  <ol class="carousel-indicators">
	    <li data-target="#carousel-structuregallery" data-slide-to="0" class="active"></li>
	    <li data-target="#carousel-structuregallery" data-slide-to="1"></li>
	  </ol>

	  <!-- Wrapper for slides -->
	  <div class="carousel-inner" role="listbox">
	    <div class="item active">
		  <a href="/images/4hhb/4HHB_Rainbow.jpg" data-toggle="lightbox" data-title="Biological Assembly 1 for 4HHB" data-footer="Protein chains are colored from the N-terminal to the C-terminal using a rainbow (spectral) color gradient">
	      	<img src="/images/4hhb/4HHB_Rainbow.jpg" alt="Biological Assembly 1 for 4HHB" class="img-responsive">
		  </a>	
	      <div class="carousel-caption">
	        Biological Assembly 1
	      </div>
	    </div>
	    <div class="item">
		  <a href="/images/4hhb/4HHB_Rainbow.jpg" data-toggle="lightbox" data-title="Asymmetric Unit for 4HHB" data-footer="Protein chains are colored from the N-terminal to the C-terminal using a rainbow (spectral) color gradient">
	      	<img src="/images/4hhb/4HHB_Rainbow.jpg" alt="Asymmetric Unit for 4HHB" class="img-responsive">
		  </a>
	      <div class="carousel-caption">
	        Asymmetric Unit
	      </div>
	    </div>

	  </div>

	  <!-- Controls -->
	  <a class="left carousel-control" href="#carousel-structuregallery" role="button" data-slide="prev">
	    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
	    <span class="sr-only">Previous</span>
	  </a>
	  <a class="right carousel-control" href="#carousel-structuregallery" role="button" data-slide="next">
	    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
	    <span class="sr-only">Next</span>
	  </a>
	</div>
	
	
  </div>	
  <div class="panel-footer">
	<p><i class="fa fa-cube"></i> <strong>3D View</strong>: <a href="#">JSmol</a> or <a href="#">PV</a> (in browser)</p>
	<p class="hidden-sm hidden-xs"> <span class="hide glyphicon glyphicon-download-alt" aria-hidden="true"></span> <strong>Standalone Viewers</strong>:</p>
	<ul class="hidden-sm hidden-xs list-inline">
		<li><a href="#">Simple Viewer</a></li>
		<li><a href="#">Protein Workshop</a></li>
		<li><a href="#">Kiosk Viewer</a></li>
	</ul>
	<hr>
	<p><strong>Symmetry</strong>: C2 (<a href="#">View in 3D</a>)</p>
	<p><strong>Stoichiometry</strong>: Hetero 4-mer - A2B2</p>
	<p>Biological assembly 1 assigned by authors and generated by PISA (software)</p>
	
  </div>
</div>


<div class="well well-sm">
	<p><strong>Structure Content</strong>: </p>
	<ul class="list-inline"> 
		<li>Proteins #: <a href="#">2</a></li>
		<li>Ligands #: <a href="#">2</a></li>
		<li class="hide">Nucleic Acids #: 0</li>
	</ul>
	<hr>
	<p><strong>Related Molecule of the Month</strong>: </p>
	<ul class="list-inline">
		<li><a href="http://www.rcsb.org/pdb/101/motm.do?momID=41">Hemoglobin</a></li>
		<li><a href="#">PDB Pioneers</a></li>
		<li><a href="#">Erythrocruorin</a></li>
	</ul>
</div>